server {
    listen 80;

    client_max_body_size 50M;
    # 1. Serve React App
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html; # مهم جداً عشان الـ React Router
    }

    # 2. Proxy Requests to Backend
    location /api/ {
        # 'backend' here is the service name from docker-compose
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}